### ISSUE TITLE
Customize navi bar's name

### ISSUE THREAD

**Issue by jackwu925** [hugo-toha/toha#1010]
### Question
Do we have any method to customize the name of "Posts"? For example, change the name "Posts" on the main page into "Thoughts".
![image](https://github.com/user-attachments/assets/12bc7dcc-db14-4539-b885-23c190e8968b)

**Comment by jamesdeluk** [comment]
I was thinking about this a couple of days ago. Even changing it to "All Posts" would be nice.

**Comment by hossainemruz** [comment]
@jackwu925 You can do that by setting title for blog on your `hugo.yaml` or `config.yaml` file.
```yaml
params:
  features:
    blog:
      enable: true
      showAuthor: true
      title: Thoughts
```
