### ISSUE TITLE
Feature Request: Dark-theme Logo

### ISSUE THREAD

**Issue by jamesdeluk** [hugo-toha/toha#1013]
### Describe the solution you'd like

Currently the logo on the home page is the same regardless of theme:

```yaml
params:
  logo:
    main: logo.png
```
If the logo is dark, and the theme is switched to dark mode, the background behind the logo goes dark, which can obscure the logo.

As such, I propose an option to set a different logo for dark mode.

### Describe alternatives you've considered

A CSS filter partially works, but is not ideal:

```css
html[data-theme="dark"] .home img {
  -webkit-filter: invert(1);
  filter: invert(1);
  background-color: #xxxxxx; /* invert of dark mode colour */
}
```

### Additional context

Slightly related to #902
