### ISSUE TITLE
Disable dark mode theme

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#1015]
Hi folks!

I’m trying to disable the dark mode theme on my website, but it’s not working as expected. Under the dark theme, the font color makes my website almost unreadable. I attempted to fix this issue, but my efforts haven’t been successful so far. Previously, my website always displayed in light mode, even for users whose browsers were set to dark mode by default. However, at some point, it started defaulting to dark mode instead.

Could anyone help me figure out how to resolve this? For reference, I’ve attached the relevant section of the YAML site parameters below:

```
# Site parameters
params:
  background: "images/iheobackground.png"
  
  logo:
    main: images/iheoma.png
    inverted: images/iheoinv.png
    favicon: images/iheofavi.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/ihnwhiheo/ihnwhiheo.github.io

  feature:
    blog:
      enable: false
    toc:
      enable: true
    theme:
      light: true
      dark: false

    # Enable Analytics
    analytics:
      enabled: false
      services:
        # Google Analytics
        google:
          id: UA-157585884-1
  footer:
    enable: true
    newsletter:
      enable: false
```

Thank you in advance!

**Comment by IhnwhiHeo** [comment]
Could this issue be related to the dark mode functionality?
Tagging @hossainemruz and @tanishkagupta27 for their insights (it might be connected to [this issue](https://github.com/hugo-toha/toha/issues/993)).

**Comment by hossainemruz** [comment]
You have to update the theme version. This setting was introduced in `v4.6.0`. You are using `v4.5.0`.
https://github.com/hugo-toha/toha/releases

**Comment by IhnwhiHeo** [comment]
Gotcha, thank you! If you do not mind, could you please make a PR for the update to my theme; or a quick shortcut of easily doing that? My toha is different from the usual version due to my previous issues..

**Comment by hossainemruz** [comment]
Sorry. Don't have time for that. Just run these commands.
```
hugo mod get
hugo mod tidy
hugo mod npm pack
npm install
```

**Comment by IhnwhiHeo** [comment]
No problem! I will run that, thank you so much @hossainemruz.

**Comment by IhnwhiHeo** [comment]
A quick follow-up:
I got a message from the terminal, saying:
```
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.
```
How may I solve this issue? Thank you in advance!

**Comment by hossainemruz** [comment]
What is your Hugo version? Make sure you are running these commands at the root of your repository.

**Comment by IhnwhiHeo** [comment]
I tried again after setting the root at my repository. Now, I get this message:
```
WARN 2024/12/02 11:21:09 Module "github.com/hugo-toha/toha/v4" is not compatible with this Hugo version; run "hugo mod graph" for more information
```
Could you please check this?

Is this error due to [this issue](https://github.com/hugo-toha/toha/issues/966)?

**Comment by IhnwhiHeo** [comment]
Of course, after running hugo version,  says the version is v0.110.0+extended darwin/arm64 BuildDate=unknown
Thank you for asking.

**Comment by hossainemruz** [comment]
In the updated theme, the Minimum supported Hugo version is `1.28.0`.
https://github.com/hugo-toha/toha/blob/4e4acdbb6b6b5f5a031ac1f4dedfeea7c1d6792c/hugo.yaml#L3

**Comment by IhnwhiHeo** [comment]
Okay, I tried:
1. Updating hugo
2. Updating the toha theme
3. Changing the hugo.yaml with the addition of min: "0.128.0"

But the website is not updated with the messages here: https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/12126762390

Can you please check this?

**Comment by IhnwhiHeo** [comment]
Yes I did.

**Comment by hossainemruz** [comment]
Please, update `module` section of your `hugo.yaml` file with this.
```
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icons/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts
```

Then, run the following commands:
```
hugo mod get
```

```
hugo npm mod pack
```

```
npm install
```
