### ISSUE TITLE
Background change request

### ISSUE THREAD

**Issue by jackwu925** [hugo-toha/toha#1023]
Hello, is there any code which can be used to customize the background? (including the dark mode and the light mode)

**Comment by BernatBC** [comment]
You can change the background by setting the following into your `hugo.yaml` file:
```yaml
# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg
```
You can take a look at the example file in https://github.com/hugo-toha/hugo-toha.github.io/blob/main/hugo.yaml

If I'm not mistaken, at the moment there isn't the option to set a different background between light and dark mode

**Comment by BernatBC** [comment]
I've made a PR #1024. Once that's merged, you can specify the dark background by setting:
```yaml
# Site parameters
params:
  # Background image of the landing page
  background: "images/background.jpg"
  darkBackground: "images/background_dark.jpg"
```
