### ISSUE TITLE
Google analytics support seems to be broken

### ISSUE THREAD

**Issue by tduchateau** [hugo-toha/toha#1053]
Hi!

Support for analytics seems to be broken for me.

By following documentation and looking at various issues, I've tested several configurations, but with no success.

Test 1, in my `hugo.yaml` file: 
````
params:
  features:
    analytics:
      enable: true
      services:
        google:
          id: G-GBN86LC9K4
````

Test 2, in my `hugo.yaml` file: 
````
services:
  googleAnalytics:
    id: "G-GBN86LC9K4"

params:
  features:
    analytics:
      enable: false
````

But I can't see any partial being included with the googletagmanager stuff.

Can anyone help me?

Hugo version: 0.147.2
Toha theme: 4.9.0

I'd like to take this opportunity to thank you for all your work!
