### ISSUE TITLE
Question: the release time of Publications Section?

### ISSUE THREAD

**Issue by fiveflowers** [hugo-toha/toha#127]
### Question

First of all, I **REALLY LIKE**  this theme. We tried this theme on the homepage of our laboratory and it has been well received by everyone.

Considering the content display, we need a module to list our papers. Our current approach is to modify the Project Section, but the performance is not good. I just saw that there is a development plan for the **Publications Section** in the roadmap and I want to ask when it will be released.

**Comment by hossainemruz** [comment]
>I just saw that there is a development plan for the Publications Section in the roadmap and I want to ask when it will be released.

I am not sure when I can work on it. Actually, not many user requested for this feature. So, it didn't have high priority for me.

Btw, which information do you think important for a paper section?

**Comment by fiveflowers** [comment]
Thanks Reply.

Personally, it is sufficient that the following key information can be presented:
- title
- authors
- name of journal or conference
- link
- year (filter)
- github star (optional, some paper may release codes as support material, especially in the field of ai)

In fact, **Project Section** is nearly functional enough, but the style needs some tweaking. For a list of papers, a long bar style would be better.

Give some examples: 
[https://www.vipazoo.cn/index_en.html#publications](https://www.vipazoo.cn/index_en.html#publications)
[http://www.seas.ucla.edu/~lu/#publication](http://www.seas.ucla.edu/~lu/#publication)

**Comment by hossainemruz** [comment]
I was thinking something like this but with project like filtering: https://themes.gohugo.io//theme/academic/#featured

**Comment by hossainemruz** [comment]
@fiveflowers Here, is an rough estimation what I am planning to do for Publication Section. Let me know what else you want to add or remove.

![Publication 1](https://user-images.githubusercontent.com/12577390/99127690-1f955500-2633-11eb-9973-3c321da93b59.png)

After clicking a paper card, a new dedicated page will open for this paper.
![Publication 2](https://user-images.githubusercontent.com/12577390/99127701-2754f980-2633-11eb-8586-eb1e00ad6aea.png)

**Comment by hossainemruz** [comment]
Some sections will be optional i.e. Awards, Gallery, Resource Links, Related Papers etc.

**Comment by fiveflowers** [comment]
Wow! This is great!
These new features have exceeded my expectations and I'm even more excited for the release of this section.

From my own perspective, there is one detail that could be modified:
- For paper card, it would be nice to show the author's name directly.
  - layout: it's best to have the author's name as a separate line, just below the title.
  - link: author's name should ideally be able to support links to the respective home page.

**Comment by hossainemruz** [comment]
@fiveflowers This is how it going to look like with author information in the cards.
![Publication 1 (1)](https://user-images.githubusercontent.com/12577390/99181861-7bf39400-275b-11eb-90b5-4e231ee138ab.png)

**Comment by fiveflowers** [comment]
I think it's good, and look forward to the release

**Comment by ipankajsingh** [comment]
> @fiveflowers This is how it going to look like with author information in the cards.
> ![Publication 1 (2)](https://user-images.githubusercontent.com/12577390/99182088-f7097a00-275c-11eb-8494-b058d150aa7f.png)

Can we have an option to open a 3rd party link once we click on the card ? Many people have published a paper in one of the international journals including me, and I would like to directly point them to that site, instead of writing a dedicated post about it and taking my users there.

**Comment by hossainemruz** [comment]
Sure @ipankajsingh. It's a good point.

**Comment by dleopold** [comment]
Is there any update on this feature being officially added to the theme?

**Comment by hossainemruz** [comment]
Nope

**Comment by mangla-sarvesh** [comment]
Can I get this feature unofficially then :-)

**Comment by mangla-sarvesh** [comment]
> @fiveflowers This is how it going to look like with author information in the cards. ![Publication 1 (2)](https://user-images.githubusercontent.com/12577390/99182088-f7097a00-275c-11eb-8494-b058d150aa7f.png)

Can you provide this feature, it is very important section for my work

**Comment by hossainemruz** [comment]
I will try in this month. Remind me if I don't. :P

**Comment by mangla-sarvesh** [comment]
> 

I  will  remind you every week. :-P

**Comment by mangla-sarvesh** [comment]
Gentel Reminder 

> I will try in this month. Remind me if I don't. :P

**Comment by hossainemruz** [comment]
I have started working already. PR coming soon.

**Comment by hossainemruz** [comment]
Added in this PR: https://github.com/hugo-toha/toha/pull/620

This is how it is going to look:

![image](https://user-images.githubusercontent.com/12577390/181590896-83218c95-b589-4cef-8161-57ab92ccc8c2.png)

This is how you are going to use:

```yaml
# section information
section:
  name: Publications
  id: publications
  enable: true
  weight: 5
  showOnNavbar: true
  # Can optionally hide the title in sections
  # hideTitle: true

# filter buttons
buttons:
- name: All
  filter: "all"
- name: "Machine Learning"
  filter: "machinelearning"
- name: "Image Processing"
  filter: "image-processing"
- name: Security
  filter: "security"

# your publications
publications:
- title: An Example Paper on Machine Learning
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Voluptate in id id voluptate laboris. Minim mollit aliquip sit aliqua ut exercitation voluptate eiusmod consequat pariatur sunt enim veniam. Velit esse tempor laboris anim tempor officia. Magna non labore duis do esse sit do ipsum culpa. Officia consequat id non duis culpa dolor. Excepteur magna non nostrud cupidatat aute aliqua aliquip.
    url: https://example.com
  categories: ["machinelearning","image-processing"]
  tags: ["Machine Learning", "Autonomous Driving", "Computer Vision"]

- title: An Sample Paper on Image Processing
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Ullamco magna minim cupidatat Lorem ea ex aliqua fugiat et. Dolor quis cillum ea duis irure et commodo aliquip consectetur ullamco labore ut anim nisi. Commodo reprehenderit est consectetur tempor adipisicing occaecat exercitation amet do aliquip dolor do irure. Labore officia ut magna pariatur reprehenderit et ex sit sunt. Magna proident ullamco adipisicing sit.
    url: https://example.com
  categories: ["image-processing"]
  tags: ["Image Processing", "Computer Vision"]

- title: An Example Paper on Security
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Dolor ad cupidatat pariatur nulla ipsum ex ullamco nisi anim ullamco. Dolore elit esse in exercitation minim aliqua. Amet velit incididunt magna laboris. Proident reprehenderit deserunt ad officia duis dolor. Tempor nostrud ullamco ullamco sint deserunt cupidatat irure minim consectetur nulla adipisicing sunt.
    url: https://example.com
  categories: ["security"]
  tags: ["Machine Learning", "Autonomous Driving", "Machine Vision"]
```
Does it work for you @mangla-sarvesh?

There are still few things missing (probably another day):
- Paginate when there are many items
- Dedicated page for publications
