### ISSUE TITLE
Translation Question: Flags

### ISSUE THREAD

**Issue by cmarquezrusso** [hugo-toha/toha#159]
### Question: How to change the country flag?

I am running my site on Spanish and English, but I will like to use the Argentinian and New Zealand flags instead of the default ones (Spain and the UK)

How can I implement this change?

**Comment by hossainemruz** [comment]
Maybe we can add a  `flagOverwrites` field in the params section of `config.yaml`.

Something like this:
```yaml
params:
  flagOverwrites:
  - languageCode: en
    countryCode: arg
  - languageCode: es
    countryCode: nzl
```
