### ISSUE TITLE
Can't set the hero image for posts. 

### ISSUE THREAD

**Issue by davidgs** [hugo-toha/toha#223]
## Expected Behavior
```
---
title: "DevRel"
date: 2020-06-08T08:06:25+06:00
description: Developer Relations
hero: watch.jpg
menu:
  sidebar:
    name: DevRel
    identifier: devrel
    weight: 30

math: true
---
```

should use the image `watch.jpg` as the hero image. 

## Current Behavior

That image is not shown. Changing the name of that file to `hero.jpg` will cause it to be shown as the hero image but that *only* works in top-level posts. If posts are in a category, or a sub-category, no combination of directories or image names seems to work and the *only* image ever shown is `default-hero.jpg`

## Possible Solution
Haven't found one yet. 

## Steps to Reproduce

1. Create a post
2. set the `hero` field to point to an image
3. that image will NOT be used
4.

### Browsers Affected

- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ X] Safari 11
- [ ] Safari 10
- [ ] IE 11
