### ISSUE TITLE
Posts returning 404 page not found

### ISSUE THREAD

**Issue by mmanueljoao** [hugo-toha/toha#253]
### Question

**I think I'm in need of some help.** 
First of all, here is my directory tree ...
![imagem](https://user-images.githubusercontent.com/6817527/111686906-90d35780-8821-11eb-9d22-4387f90ea27b.png)

I have added only the example posts so I could teste before launching and, somehow, my `hugo server -D` isn't able to show me the posts. And yes, in the `config.yaml` I have the `  enableBlogPost: true`.

Right now, this is the output of the `hugo server -D`:
![imagem](https://user-images.githubusercontent.com/6817527/111687573-54542b80-8822-11eb-9f5d-ceca09a5baa1.png)

And of course, the error and locations that the site is trying to reach:
![imagem](https://user-images.githubusercontent.com/6817527/111687820-a301c580-8822-11eb-8eb4-f550c77fa064.png)

**_Any idea of what can be wrong?_**

**Comment by hossainemruz** [comment]
Can you share the `config.yaml` file? Also, please share the repository link if possible.

**Comment by mmanueljoao** [comment]
Yes, sorry! 
Here is the link : https://github.com/mmanueljoao/mjoaolima.eu

and the config.yml
```
baseURL: https://mjoaolima.eu

languageCode: en
title: "a personal space | in main"
theme: "toha"


# disableLanguages: pt
languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
  pt:
    languageName: Português
    contentDir: content/pt
    weight: 2

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false

outputs:
  home:
    - HTML

enableEmoji: false

params:
  enableBlogPost: true

  enableTOC: true

  newsletter:
    enable: false

  background: images/site/background.jpg
```
