### ISSUE TITLE
Add feature control configuration in config.yaml

### ISSUE THREAD

**Issue by hossainemruz** [hugo-toha/toha#267]
```yaml
enableFeatures: ["portfolio", "blog", "notes", "documentation"]
```

**Comment by Kaligule** [comment]
Alternatively you could allow to enable them one by one:
```yaml
portfolio:
  enable: true
blog:
  enable: true
  some_blog_feature: 7
```
This is how it is done in nixos and it is a cool way to have the configuration of the feature and the enabling of the feature in one place.
