### ISSUE TITLE
Prev button displays two words with different languages

### ISSUE THREAD

**Issue by IshoAntar** [hugo-toha/toha#346]
## Expected Behavior
The text should be displayed in a single (configured) language.

## Current Behavior
The text on the "Prev" button should display a single word in the configured language.

This is only happening on the last (newest) post, where the button points to the "search" function.

## Possible Solution
Remove the extra word. Or remove the button all together since it points to the search function which is misleading since it says "Prev".

## Steps to Reproduce

1. `hugo new site test`
2. `cd test && git clone https://github.com/hugo-toha/toha.git themes/toha`
3. Add the following to `config.yml`:
```yaml
baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

theme: toha

params:
  enableBlogPost: true
  enableTOC: true
```
4. `hugo new posts/intro/index.md`
5. Navigate to `localhost:1313/posts/intro`

### Screenshots
![2021-06-04_19-09](https://user-images.githubusercontent.com/32076082/120814746-74f16f00-c54f-11eb-987a-644ac30d82ca.png)

### Browsers Affected

- [x] Chromium
- [ ] Chrome (didn't test)
- [x] Firefox
- [ ] Edge (didn't test)
- [ ] Safari 11 (didn't test)
- [ ] Safari 10 (didn't test)
- [ ] IE 11 (didn't test)
