### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#387]
### Describe the solution you'd like

Is it possible to add a last modified time to the article？
### Describe alternatives you've considered

I added the code in the following location , but the last modification time of the file cannot be read automatically, only the manual modification time is available.
`config.yaml`
```
  frontmatter:  # 意为，变量 .Date 将会被赋值为 数组中最先找到的的日期值
    date: [":filename","date","publishDate","lastmod"]
    lastmod: [":fileModTime",":git","lastmod","date","publishDate"]
    publishDate: ["publishDate","date"]
    expiryDate: "expiryDate"
```
`\layouts\_default\single.html`
```
      <!--Content Start-->
      <div class="page-content">
        <div class="author-profile ml-auto align-self-lg-center">
          <img class="rounded-circle" src='{{ partial "helpers/get-author-image.html" . }}' alt="Author Image">
          <h5 class="author-name">{{ partial "helpers/get-author-name.html" . }}</h5>
          <p>{{ .Page.Date.Format "January 2, 2006" }}</p>
          <p>{{ .Page.Lastmod.Format "January 2, 2006" }}</p>
        </div>
```
I am not a professional programmer, I don’t know what went wrong, I hope it can be solved
### Additional context

This is the style of my current blog
![image](https://user-images.githubusercontent.com/29678677/127763228-8e96832b-c0a4-46a4-a9f6-2b2270a01cad.png)
@hossainemruz

**Comment by hossainemruz** [comment]
You have to set `enableGitInfo: true` in your `config.yaml` file.
Ref: https://gohugo.io/variables/git/#gitinfo-prerequisites

**Comment by Chow-Ray** [comment]
> You have to set `enableGitInfo: true` in your `config.yaml` file.
> Ref: https://gohugo.io/variables/git/#gitinfo-prerequisites

Sorry, after I configured `enableGitInfo: true` in my `config.yaml` file., it still doesn't work😢

**Comment by Rihoj** [comment]
@Chow-Ray I followed the steps you listed above and I get the file's last modified time showing. 
![image](https://user-images.githubusercontent.com/1520296/128646807-765448f5-2029-4d2b-95fd-ae467e14ec5f.png)

If you could give more details as to what you are seeing I might be able to help

**Comment by Chow-Ray** [comment]
@Rihoj ，Thank you so much for helping me！
config.yaml
```
enableGitInfo: true
params:
  frontmatter:  # 意为，变量 .Date 将会被赋值为 数组中最先找到的的日期值
    date: [":filename","date","publishDate","lastmod"]
    lastmod: [":fileModTime",":git","lastmod","date","publishDate"]
    publishDate: ["publishDate","date"]
    expiryDate: "expiryDate"
```

Front Matter
```
---
title: "Hugo Front Matter"
date: 2021-08-05T18:14:05+08:00
lastmod: 
description:  #描述
keywords:  #关键词
tags: 
categories: 
draft: false
hero: #/assets/images/background/sunrise.jpg  # 文章背景
author:
    name: # 文章作者
    image: #/assets/images/profile-image.jpg  # 作者头像
menu:
  sidebar:
    name: "Hugo Front Matter"
    identifier: "2021 08 05 Hugo_Front_Matter"
    parent: it
    weight: 20210805
---
```

**Comment by Chow-Ray** [comment]
@Rihoj 
The about page can automatically display the modification time, like the second picture.
The page in the post cannot automatically display the modification time, like the third picture.
![image](https://user-images.githubusercontent.com/29678677/128697152-056215bc-40f4-420b-81db-458114077c10.png)
![image](https://user-images.githubusercontent.com/29678677/128697240-982b7785-6f00-41d2-a37c-efa14adb172a.png)
![image](https://user-images.githubusercontent.com/29678677/128697450-aaa64531-a6b5-48db-b385-422f65f682c5.png)

**Comment by Rihoj** [comment]
@Chow-Ray Try moving the frontmatter configuration outside of the params. Mine file is setup as:

```yaml
enableGitInfo = true
frontmatter:
  date: [":filename","date","publishDate","lastmod"]
  lastmod: [":fileModTime",":git","lastmod","date","publishDate"]
  publishDate: ["publishDate","date"]
  expiryDate: "expiryDate"
params:
  gitRepo = "https://github.com/..."
```

The repo url is not required for this, but was included for reference.
