### ISSUE TITLE
The navigation bar does not display the notes/posts button text

### ISSUE THREAD

**Issue by ormissia** [hugo-toha/toha#388]
## Expected Behavior

Set defaultContentLanguage: cn in config.xml

## Current Behavior

The navigation bar does not display the notes/posts button text, [for EX.](https://ormissia.github.io)
But the link still exists

Maybe since 2021-7-30~2021-8-1

[My complete config file](https://github.com/ormissia/ormissia.github.io/blob/cd85c9812c1b54474c109b9a93b6440786ca5bef/config.yaml#L5)

> fragment
```yaml
languageCode: en-us
# 默认语言修改为中文
defaultContentLanguage: cn
# 页面左上角和标签栏的标题标题
title: "Ormissia's Blog"
# 主题
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  cn:
    languageName: 中文
    weight: 1

```

[I enabled posts/notes](https://github.com/ormissia/ormissia.github.io/blob/cd85c9812c1b54474c109b9a93b6440786ca5bef/config.yaml#L58)

> fragment
```yaml
  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
    # Enable & configure "Notes" features
    notes:
      enable: true
```

## Possible Solution

Sorry, I have no idea.

## Steps to Reproduce

1.
2.
3.
4.

### Screenshots

<img width="753" alt="image" src="https://user-images.githubusercontent.com/55517494/127798642-b9e7a7a5-439e-43d7-b67f-da7253b9a8fc.png">

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 11
- [ ] Safari 10
- [ ] IE 11
