### ISSUE TITLE
socialLinks don't display

### ISSUE THREAD

**Issue by DocKDE** [hugo-toha/toha#411]
Hi,
I've been following the docs and stumbled across this issue. My `about.yaml` file looks like this:

```
section:
  name: About me
  id: about
  enable: true
  weight: 1
  showOnNavbar: true
  template: sections/about.html

designation: "My Profession"
company:
  name: "My Company"
  url: "https://someurl.com"

resume: "files/cv_english.pdf"

summary: "I am a test person." 

socialLinks:
- name: Email
  icon: "fas fa-envelope"
  url: "mail@test.com"

- name: Github
  icon: "fab fa-github"
  url: "https://github.com/hugo-toha/toha"

softSkills:
- name: Leadership
  percentage: 50
  color: blue
- name: Team Work
  percentage: 65
  color: red
```

And everything is fine, except the social Links are not displayed. I took this part from here: https://toha-guides.netlify.app/posts/getting-started/prepare-site/#about-section. Am I missing something here?
