### ISSUE TITLE
Adding Commento.io support

### ISSUE THREAD

**Issue by KHannibal** [hugo-toha/toha#562]
### Describe the solution you'd like

I would like toha to support [Commento.io](https://commento.io) comment system, please. 

### Describe alternatives you've considered

None, but I am currently using Commento and migrating all the comments to another platform would be very time consuming.

### Additional context

None.

**Comment by hossainemruz** [comment]
This does not seems to have a free tier. It won't be possible for us to test the commenting system. It has 30 days trial which can help initial setup part. However, we won't be able to test whether it works or not after that trial period.

**Comment by KHannibal** [comment]
Thanks you @hossainemruz for the quick reply. Let me know if I can help with the testing (provided you tell me what to do, as I am not a dev).

**Comment by hossainemruz** [comment]
Can you test #564 PR? Go to `themes/toha` folder and checkout to `commentio` branch. Then, add commento configuration under `params.features.comment` section of your `config.yaml` file.

```yaml
params:
  features:
    comment:
      enable: false
       commento:
         serverURL: cdn.commento.io
         autoInit: true
         hideDeleted: false
```
