### ISSUE TITLE
Doesn't recognize images if the markdown metadata is indented

### ISSUE THREAD

**Issue by AngelicaRibeiro** [hugo-toha/toha#578]
## Expected Behavior
The thumbnail images are recognized if the  metadata information  is not indented like:
```
title: "Rich Content"
date: 2020-06-08T08:06:25+06:00
description: Sample post with multiple images, embedded video ect.
menu:
  sidebar:
    name: Rich Content
    identifier: rich-content
    parent: sub-category
    weight: 10
hero: images/forest.jpg
tags: ["Markdown","Content Organization","Multi-lingual"]
categories: ["Basic"]
---
```
![image](https://user-images.githubusercontent.com/13433634/162328274-a7233b41-1f7b-48f4-b99f-48127840ec18.png)

## Current Behavior

but if the data is indented, for example in visual studio:
```
---
title: Rich Content
date: 2020-06-08T02:06:25.000Z
description: Sample post with multiple images, embedded video ect.
menu:
  sidebar:
    name: Rich Content
    identifier: rich-content
    parent: sub-category
    weight: 10
hero: images/forest.jpg
tags:
  - Markdown
  - Content Organization
  - Multi-lingual
categories:
  - Basic
modified: 2022-04-07T22:11:09.100Z
---
```
![image](https://user-images.githubusercontent.com/13433634/162328848-b1fec448-1da1-4da8-aa85-69e8b35ea1ee.png)

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
