### ISSUE TITLE
Is there a way to disable the newsletter signup element in bottom bar?

### ISSUE THREAD

**Issue by jonathanlang** [hugo-toha/toha#626]
### Question
Hi, I don't see a way to disable the sign-up form asking for email addresses to keep the user posted. 
I don't want or need this on my site, and it doesn't seem to work anyways, but I can't figure out what I need to set where to disable it. 
Can anyone provide me with a hint? 
Thanks!

**Comment by hossainemruz** [comment]
Just set this to false.
https://github.com/hugo-toha/hugo-toha.github.io/blob/87003c8b898bc51881fd7c64d06d67a9f6b37774/config.yaml#L183

**Comment by jonathanlang** [comment]
Hm, it doesn't seem to be having any effect for me. 
I'm working in /config.yaml. 
This is the structure of my yaml, but changing the enabled parameter under footer doesn't change the page: 

```
baseURL: XXX
languageCode: en-us
title: "XXX"
theme: "toha"

markup:
  goldmark:
    renderer:
      unsafe: false

enableEmoji: true

params:
  copyright: XXX
  background: "images/background.jpg"
  enableBlogPost: false
  footer:
    enable: false
```
