### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jonathanlang** [hugo-toha/toha#629]
### Describe the solution you'd like

When customizing the parameters of a section, I would like to be able to rename the header, which shows up in the title of the section as well as the navigation. 
```
# section information
section:
  name: Experiences
  enable: true
  weight: 3
  showOnNavbar: true
```

I would expect when I type in something under the name parameter, that would be reflected. Instead it seems this name is hardcoded to the yaml file and changing it breaks the generator, since it's looking for the yaml file under a different filename then. 

### Describe alternatives you've considered

Maybe either introduce a title tag that is separate, or take the filename of the yaml as reference and allow customization of the name tag.
