### ISSUE TITLE
softSkills text does not wrap correctly

### ISSUE THREAD

**Issue by quantitative-technologies** [hugo-toha/toha#643]
## Expected Behavior

Text should wrap so that it is fully visible and not covered up by the outer circle.

## Current Behavior

The text "Machine Learning" is not wrapped and the initial 'M' and terminal 'g' are partially covered. 

I also cannot find any way to force the text to break in between the two words. It looks like this: 

![bug-report-toha-softSkills](https://user-images.githubusercontent.com/29150871/188862382-dcc61ddf-cbbe-4ce0-9245-8113a9e245dd.png)

## Possible Solution

Don't know

## Steps to Reproduce

Relevant section of my `about.yaml`:

```yaml
softSkills:
- name: Machine Learning
  percentage: 85
  color: blue
```
