### ISSUE TITLE
Contacts list doesn't work as shown in documentation

### ISSUE THREAD

**Issue by SrNetoChan** [hugo-toha/toha#656]
### Question

I am not sure if it's a bug or actually a feature request, but following documentation - 
https://toha-guides.netlify.app/posts/configuration/site-parameters/#add-author-information - I seemed to me that adding new items to the contact list would be possible, like for example:

```yaml
  stack-overflow:
    icon: stack-overflow
    url: "https://stackoverflow.com/users/1/exampleUser"
    text: "ExampleUser"
```
Nevertheless, when I try to use that, I don't get it to render correctly.

![image](https://user-images.githubusercontent.com/3607161/193962157-2b419bbe-de58-4db1-809b-b1f689271869.png)

Should I open a ticket?
