### ISSUE TITLE
Duplicate "Experiences" section 

### ISSUE THREAD

**Issue by El-Gavy** [hugo-toha/toha#691]
Hello,

First of all, thank you very much for this great theme! 

However, I have a question: I have a lot of volunteer activities and I would like to be able to separate them from my professional experiences. I think the cleanest way to do this is to duplicate the "Experiences" section. Is this possible? If so, how do I do it?

Thanks!

**Comment by hossainemruz** [comment]
Just add another data file for new experience section in your data folder. For example, add `volunteer-activities.yaml`

```yaml
# section information
section:
  name: Volunteer Activites
  id: volunteer-activites
  template: sections/experiences.html
  enable: true
  weight: 4
  showOnNavbar: true

# Your experiences
experiences:
# Your experiences here
```
