### ISSUE TITLE
Process completed with exit code 255

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#738]
Hi Toha folks,

I have been facing the following error messages when I try to build and update my website using GitHub Actions: Process completed with exit code 255.

For example, please see my recent trials:
- https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/4276234584
- https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/4276273848
- https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/4276336624
Not sure if this only applies to me or not; but how can I handle this?
Thank you!

** I am using Mac to build my website.

**Comment by hossainemruz** [comment]
Hi @IhnwhiHeo, we have made some changes in how the theme is used. We have moved from git sub module to Hugo modules.

**Comment by IhnwhiHeo** [comment]
Hi @hossainemruz, thank you for letting me know! I will check the Usage section and let me ask you if I find anything unclear.

Cheers,
Ihnwhi

**Comment by hossainemruz** [comment]
Be aware that configuration format has changed. You might have to change quite a few things. If you don't need any newer features and happy with your existing site, I will recommend to disable auto-updating using dependabot and stay to the latest stable release `v3.8.0`.

**Comment by IhnwhiHeo** [comment]
@hossainemruz 
I checked a bit. I have two quick questions:
- Without reforming a theme, can I still use the theme?
- If I do not use the GitHub action, how can I update my website?

**Comment by hossainemruz** [comment]
It seems you have already updated the theme to the latest commit. You have to roll-back to the latest release. I will let you know how you can you roll-back.

**Comment by IhnwhiHeo** [comment]
I see. Could you please let me know how to do that? Thanks :)

**Comment by hossainemruz** [comment]
Sure. Give me a day.

**Comment by hossainemruz** [comment]
Hi @IhnwhiHeo, created a PR to your repo upgrading the configuration to latest version. Once you merge it, you GitHub action should start work again.
- https://github.com/IhnwhiHeo/ihnwhiheo.github.io/pull/118

**Comment by IhnwhiHeo** [comment]
Hi @hossainemruz, 
Thank you so much for this! I appreciate it.
Then, from now onwards, I should not update the toha package, right?

**Comment by hossainemruz** [comment]
You can update the theme.

**Comment by IhnwhiHeo** [comment]
Hi @hossainemruz,

Thank you! I will keep updating the theme.
BTW, two additional issues arise:
- GitHub Action (pages build and deployment) again stopped working. Could you please check?
- The website cannot retrieve my resume, which is in the ``static/files`` folder.

**Comment by hossainemruz** [comment]
I will take a look at night.

**Comment by IhnwhiHeo** [comment]
Great, thank you!
FYI, [the example TOHA website](https://hugo-toha.github.io/) also stopped working for the resume part. So fixing this will be very useful.

**Comment by IhnwhiHeo** [comment]
Hi @hossainemruz,
Just wondering whether there are any updates on Resume/CV error. Hope this does not bug you too much, tho :)

**Comment by hossainemruz** [comment]
Hi @IhnwhiHeo. Sorry, I couldn't manage time to look into this issue. This week was overwhelming for me. Hopefully, I will be able to look into this issue over the weekend or next week.

**Comment by d-huck** [comment]
I think what is happening here is that the fonts are overwriting whatever is in fonts from this line in the example config:

```
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts
```

This basically is just filling the files directory with the mullish font files and nothing else.

A temporary workaround is to just change that section in `config.yaml` to

```
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts
  - source: ./static/files
    target: static/files
```

I don't know enough about Hugo to suggest a more substantial change to the theme, but I hope this helps @IhnwhiHeo in the meantime.
