### ISSUE TITLE
Unable to host website on github pages

### ISSUE THREAD

**Issue by roumail** [hugo-toha/toha#740]
### Question

Website: roumail.github.io
Source code: https://github.com/roumail/roumail.github.io

I'm able to follow the instructions and create a website that render's properly when I do it locally:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/32498483/224379408-b5eb9d08-4020-4b98-a331-9cc918291f50.png">

However, it doesn't seem to be hosted on github pages with a 404 message saying index.html not found

<img width="785" alt="image" src="https://user-images.githubusercontent.com/32498483/224379730-3b04e064-0b2e-4d98-8638-24a479c99789.png">

I'm not sure what the error is.. This is what the github pages part looks like:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/32498483/224379897-f4ba6138-6309-4759-a5c0-a36544d59c2f.png">

Any helpful tips please?

**Comment by roumail** [comment]
My current .github/workflows/deploy-site.yaml
```
name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Update Hugo Modules
      run: hugo mod tidy

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install node modules
      run: |
        hugo mod npm pack
        npm install
    - name: Build
      run: hugo --minify

    # push the generated content into the `gh-pages` branch.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        
```

Does the above configuration have any implications on how the build and deployment needs to look?

<img width="791" alt="image" src="https://user-images.githubusercontent.com/32498483/224380607-c73f8510-ca54-4457-b548-66a18b715733.png">
