### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by roumail** [hugo-toha/toha#741]
## Expected Behavior
Followed the documents for adding comments and tried disqus, utteranc and giscus to no avail.

## Current Behavior
No comments section added

## Possible Solution
I was first trying with giscus and when it didn't work with the others as well, I thought this is likely a bug.

## Steps to Reproduce
1. update config.yaml, uncommenting the relevant sections
2. follow installation steps from guide
3. load locally

### Screenshots

<img width="848" alt="image" src="https://user-images.githubusercontent.com/32498483/224461502-522eb1f9-fd5a-474b-9c9f-cb41a3afa17d.png">

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Can you please share your repo. The configuration format has changed from the documentation.

**Comment by roumail** [comment]
https://github.com/roumail/roumail.github.io

**Comment by hossainemruz** [comment]
You are using old configuration format. Please, check this new format: https://github.com/hugo-toha/hugo-toha.github.io/blob/dd88f0fb7af186f83ece20c507deac61ac324c5c/config.yaml#L116

**Comment by roumail** [comment]
Yes, indeed it works now, What about the section. Is this part of the new or old config?

```
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts
```
