### ISSUE TITLE
Skills logo misaligned

### ISSUE THREAD

**Issue by mmzeynalli** [hugo-toha/toha#753]
## Expected Behavior

In the skills section, when I put a logo to a skill, but logo appears to be a little below than text, however, it should be at the same height. My image is transparent, the square logo of C prog language.

## Current Behavior

My logo is below the text, which is not good visually.

## Steps to Reproduce

```
skills:
  - name: C
    logo: "/images/sections/skills/c.png"
    summary: "Using as the main language for professional development. Capable of writing scalable, testable, and maintainable programs."
```

### Screenshots

![image](https://user-images.githubusercontent.com/33568903/233835935-02b64db2-5132-4c1d-a46c-a4198a5658f0.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

Here is the link to my repo:
https://github.com/mmzeynalli/mmzeynalli.github.io
