### ISSUE TITLE
Feature request about section Experiences (show logo company)

### ISSUE THREAD

**Issue by niltied** [hugo-toha/toha#871]
Hi @hossainemruz 

After all the work done on Toha v4, I think, it's time to make evolution on the frontend of Toha. 

So, first, i closed my initial issue #827. Because, i'm not satisfy about the content of this issue, and I'm not an developer. I feel not be able to dev this feature. So, i make this new issue with more explications here for any people.

### Definition of Ready

I would like to have the possibility to add the logos of the companies where I worked in the `Experience` section. I've put an example below that describes the imagined presentation, and I've also added some sample code that might meet this need.

![toha_logo_feature](https://github.com/hugo-toha/toha/assets/92774152/2266db35-95ba-40a4-85c8-96243d05f875)

I post the code showed in the image to make it clearer.

```yaml
experiences:
  - company:
      name: Example.co
      logo: image/experience/logo.example.co.jpg
      url: https://www.example.co
      location: Washington DC
  - positions:
      designation: Software engineer
      start: Mar 2016
      end: May 2017
```
The idea is : 
* We add the path of the logo image for each experience section added in the `experience.yaml` file.
* We add the image in `asset/sections/experiences/` directory.

### Definition of Done

- [ ] Feature delivered
- [ ] Experience Guide updated

What do you think ?
