### ISSUE TITLE
Disable newsletter sign-up page after migrating to v4

### ISSUE THREAD

**Issue by zotroneneis** [hugo-toha/toha#876]
I just updated my site from v3 to v4, following the [official guide](https://toha-guides.netlify.app/posts/update-v3-to-v4/).

No matter what I do, the newsletter sign up in the footer does not disappear. Disabling the option has no effect. I already saw a related issue [here](https://github.com/hugo-toha/toha/issues/626). I believe I have the newest version of the theme. My repo is public: https://github.com/zotroneneis/zotroneneis.github.io. Could you please help?

**Comment by niltied** [comment]
Hi @zotroneneis,

It's strange. Your `config.yaml` looks OK. In my case, `params.footer.newsletter` is set to `false` too, and the newsletter sign up doesn't appear in the footer as requested. But I started from scratch to V4, not by migration way.

**Comment by BernatBC** [comment]
Hi @zotroneneis 
I've notticed that yout `footer` section in `config.yaml` is idented with an extra space, meaning `footer` is a child of `features` instead of `params`. Removing those extra spaces in the footer section should fix this issue.

**Comment by BernatBC** [comment]
This `config.yaml` works:

```yaml
baseURL:  "https://alpopkes.com"
languageCode: en-us
title: "Anna-Lena Popkes"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts
      
# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Disqus forum
# disqusShortname: www-pwenker-com
# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: "images/background/sheep.JPG" # 1920x1078

  # The inverted logo will be used in the initial transparent navbar and
  # the main logo will be used in the non-transparent navbar.
  logo:
    main: images/author/image_al.jpg
    inverted: images/author/image_al.jpg
    favicon: images/author/image_al.jpg
      
  # GitHub repo URL of your site
  gitRepo: https://github.com/zotroneneis/zotroneneis.github.io
  gitBranch: main

  # Configure various features of this theme
  features:
    # Enable and configure blog posts
    blog:
      enable: true

    # Show tags under the post title
    tags:
      enable: false

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Enable dark mode
    darkMode:
      enable: true

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: true
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\[
              right: \\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\(
              right: \\)
              display: false

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
      # provider: mailchimp
      # mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true

```
