### ISSUE TITLE
"I want to update the theme automatically, but the theme-update.yml fails."

### ISSUE THREAD

**Issue by javierasping** [hugo-toha/toha#899]
### Question

"I've noticed that the theme has been updated significantly since I forked it, and I'd like to update it. However, when I run the update script, I get the following error, and I'm not sure how to fix it."

[update-theme](https://github.com/javierasping/sentinel/actions/runs/7957106614/job/21719162030#step:7:14)
Process completed with exit code 1.
[update-theme](https://github.com/javierasping/sentinel/actions/runs/7957106614/job/21719162030)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-hugo@v2.6.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

![image](https://github.com/hugo-toha/toha/assets/80594036/e958a683-b1d7-4d9e-b5bf-f561ba48cbcd)

![image](https://github.com/hugo-toha/toha/assets/80594036/30e17c70-4bac-4bb0-8deb-3ae1ef654858)

I wanted to know if there is any way to do it manually or how to solve this error. Thank you very much in advance!! I leave you the link to the repository.

https://github.com/javierasping/sentinel

**Comment by BernatBC** [comment]
When updating the theme version to V4, some changes are required. You can follow this guide https://toha-guides.netlify.app/posts/update-v3-to-v4/

If you're still unable to fix the workflow after following the guide, please tell us.

**Comment by BernatBC** [comment]
I managed to build your site locally by removing the following lines from your `config.yaml`

```yaml
  images:
    defaultWidth: original
    defaultHeight: original
```

```yaml
      services:
        darkreader:
          defaultColorScheme: system # options are 'system', 'dark', 'light'
          fixes:
            invert: ['img[src$=".svg"]'] # inverts svg colors.
          theme:
            brightness: 100
            contrast: 100
            sepia: 0

```
