### ISSUE TITLE
Using FontAwesome icon for project card

### ISSUE THREAD

**Issue by niltied** [hugo-toha/toha#910]
Hi @hossainemruz,

# Context

When I create a new project card in `/data/en/sections/projects.yaml`, for example : 

```yaml
projects:
- name: Gaming
  role: Player
  logo: "fa-solid fa-gamepad"
  timeline: "january 2000 - Now"
  summary: "My nolife hobby"
```

I would like to illustrate my card with a Fontawesome logo, but it seems that it doesn't work for me or I haven't understood how it works.

# Questions

Toha support FontAwesome icon to illustrate the projects card ?

Another question : What is the ideal pixel size of an icon (jpg or png) for project cards ?

Thank,
