### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by mmzeynalli** [hugo-toha/toha#991]
## Expected Behavior

Is there any way to enable rss? I cannot access `localhost:1313/rss.xml` at all, gives 404.

## Current Behavior

404 page, at `/rss.xml`

### Screenshots

![image](https://github.com/user-attachments/assets/13353189-781c-4be9-af44-7fff38183aa6)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### My hugo.yaml

```yaml
baseURL: https://mmzeynalli.dev

languageCode: en-us
title: "Miradil's Blog"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
    - source: static/files
      target: static/files
    - source: ./node_modules/flag-icon-css/flags
      target: static/flags
    - source: ./node_modules/@fontsource/mulish/files
      target: static/files
    - source: ./node_modules/katex/dist/fonts
      target: static/fonts

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  az:
    languageName: Azərbaycanca
    weight: 2

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

taxonomies:
  category: categories
  tag: tags
  series: series

# Site parameters
params:
  # Background image of the landing page
  # background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/favicon.png
    inverted: /images/site/favicon.png
    favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/Miradils-Blog/website
  # Default branch of your Git repo
  gitBranch: main

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

  # Configure various features of this theme
  features:
    # Enable   theme
    theme:
      enable: true
      services:
        light: true # enable light theme. default "true"
        dark: true # enable dark theme. default "true"
        default: system # can be either light, dark or system. default "system"

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        # reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: true
      services:
        disqus:
          shortName: mmzeynalli

    # Enable Analytics
    analytics:
      enabled: true
      services:
        # Google Analytics
        # google:
        #   id: G-H4LBG7NDFZ
        # CounterDev
        # counterDev:
        #   id: <your counterdev id>
        # GoatCounter
        goatCounter:
          code: mmzeynalli
        # Matomo / Piwik
        # matomo:
        #   instance: matomo.example.com
        #   siteId: 1 # Or any other number

    # Enable Support
    support:
      enable: true
      services:
        #     kofi:
        #       user: hossainemruz
        #       text: Tip Me
        #       textColor: "#f9fafc"
        #       backgroundColor: "#248aaa"
        buymeacoffee:
          user: mmzeynalli
          text: Buy me coffee to keep me awake to write!
          info: Buy me a coffee!
          color: "#FFDD00"

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    tags:
      enable: true

    taxonomies:
      enable: true

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: true
      # # If you want to use different country flag for a language, specify them here.
      # flagOverwrites:
      #   - languageCode: en
      #     countryCode: us

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: false
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
          # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          # theme: dark

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: true
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: "\\["
              right: "\\]"
              display: true
            - left: $
              right: $
              display: false
            - left: "\\("
              right: "\\)"
              display: false

    # Enable to use custom syntax highlight
    # Please note, Hugo comes with it's own html based syntax highlighter.
    # Your code block will still be syntax highlighted by hugo.
    # For more details: https://gohugo.io/content-management/syntax-highlighting/
    # To disable Hugo's builtin syntax highlight,
    # see: https://gohugo.io/getting-started/configuration-markup#highlight
    # ```
    # # config.yaml
    # markup:
    #   # this disables hugo's syntax highlighting.
    #   codeFences: false
    # ```
    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: true
      services:
        # convert .js-player class into video player via https://plyr.io/
        # Can play HTML5 Video, Audio, Youtube, Vimeo.
        # For more info on setup: https://github.com/sampotts/plyr#quick-setup
        plyr:
          # options doc: https://github.com/sampotts/plyr#options
          # fullscreen: true

    # Enables copy code button
    copyCodeButton:
      enable: true

    # Enable reading time support in post cards and in post pages
    readingTime:
      enable: True

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true
```
